### ISSUE TITLE
Seed database with weapons

### ISSUE THREAD

**Issue by Sokojoe** [Sokojoe/cyberpunk#16]
All weapon data should be contained within a YAML file. At runtime, the server should parse this data and save it, so the server has access to weapon data.

Weapons data

```yaml
WeaponName:
  name: Weapon Name
  attackSquares: []
  attackPattern: []
  damage: Num
```

**Comment by Sokojoe** [comment]
For future reference.: 

This was completed, however, the decision was to include attackPattern as an array for each attackSquare. This way different attack squares can have different attack patterns. 

yaml looks like the following: 

```yaml
WeaponName:
  name: Weapon Name
  attackSquares: 
    - x: Num
      y: Num
      attackPattern: 
        - x: Num
          y: Num
  damage: Num
```
